### ISSUE TITLE
Problem with the <au-code> Custom ElementLook 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#114]
The autocomplete tab shows the HTML code to be 

```html
<input au-kendo-autocomplete="data-source.bind: items;" value.bind="value">
```

while the actual code is

```html
<input au-kendo-autocomplete="data-source.bind: items;" value.bind="value"></input>
```

Note the closing `</input>` tag missing. This was not the case with the previous `markdown` component - easy to verify that [here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/autocomplete)

**Comment by JeroenVinke** [comment]
I've taken a look, and can confirm what you are saying. The "missing" input tag is happening because the browser has "normalized" the HTML before it gets to the au-code custom element. <input> shouldn't have an end tag ([sample](http://www.w3schools.com/tags/tag_input.asp)).

We didn't have this problem with the textarea approach, but then we couldn't show interpolation statements because Aurelia doesn't allow this. So, there's problems with both approaches, but i'd rather have the browser normalize the HTML than not being able to show interpolation expressions.

**Comment by adriatic** [comment]
The problem with `au-code` custom element is not really a problem - we should use the "normalized" HTML code in our samples, so there would be no difference between the used code and the code rendered by `au-code`

**Comment by adriatic** [comment]
Just added the change described **[above](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/114#issuecomment-162895757)** - so closing this issue
