### ISSUE TITLE
Grid goes outside of the collapse-panel

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-kendoui-plugin#138]
![image](https://cloud.githubusercontent.com/assets/2189477/11766389/96a55358-a185-11e5-96f3-8f4e5eca1149.png)

this only happens when the height is passed in via the `bindable` height property, so the basic use example is fine

**Comment by adriatic** [comment]
Note that it was me who added the bindable declaration to height property in grid wrapper since all grids except basic (I hope that I remember that correctly, as my PC is still not cooperating with me) were way to tall

**Comment by adriatic** [comment]
There is a chance that we have a confusion here, so let's resolve it. Here is what I see happening:

1. Any grid that has the `pageable` attribute defined in the view-model:
```javascript
  pageable = {
    refresh: true,
    pageSizes: true,
    buttonCount: 5
  };
```
should have the height property undefined, meaning that it will use the grid's natural size as the definition of height.

2. Grids that do not have paging control set (like Virtualization of remote data, where this UI widget is not used intentionally) will respond to height limit (and if it set to be less than its total size, a vertical scrollbar will be added

**Now all this is very standard and surely well known** - so I am not sure why do we have "bindable" height and the height attribute that is not declared as bindable. I thought that this latter case is a mistake!?

**Comment by JeroenVinke** [comment]
In the example of [batch-editing](http://demos.telerik.com/kendo-ui/grid/editing), they use both pagination and declare a height:

```
$("#grid").kendoGrid({
    dataSource: dataSource,
    navigatable: true,
    pageable: true,
    height: 550,
    toolbar: ["create", "save", "cancel"],
    columns: [
        "ProductName",
        { field: "UnitPrice", title: "Unit Price", format: "{0:c}", width: 120 },
        { field: "UnitsInStock", title: "Units In Stock", width: 120 },
        { field: "Discontinued", width: 120 },
        { command: "destroy", title: "&nbsp;", width: 150 }],
    editable: true
});
```

So this should not cause it to go outside the collapse-panel, like I showed on the image, correct?

**Comment by adriatic** [comment]
#### Here is what I think is going on:

If the grid is pageable (which in my view means that the grid has a defined page height (number of rows per page multiplied by the row height), then its container should not define the container height; the container will adjust its height automatically. The batch-editing grid is such example because both pagesize (in view model) and height (in HTML) are defined - an we have a consistency issue resulting with a "peek"
```
 <au-kendo-grid data-source.bind="datasource" height="420" pageable.bind="true" navigatable.bind="true" toolbar.bind="['create', 'save', 'cancel']" editable.bind="true">
```
![image](https://cloud.githubusercontent.com/assets/2712405/11768805/3cb09148-a1a6-11e5-8659-8509165ceb76.png)

Removing the height definition from the markup results with a lot toller grid, which however contained correctly

![image](https://cloud.githubusercontent.com/assets/2712405/11768828/ccd133b8-a1a6-11e5-9633-13dbd2fba0bf.png)

**Comment by adriatic** [comment]
The fact is also that I am most likely the person who set `width=420` in my sweep across all grid samples, trying to make them all the similar height that fits on the screen so that the `Code View` can be seen immediately
