### ISSUE TITLE
Chart height cannot be overridden 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#161]
The rendered chart control always takes the default width defined **[here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/chart/chart.js#L31)**

Even if this **same value** is changed in the wrapper, the rendered control still has height of 400

**Comment by JeroenVinke** [comment]
stock chart also has this problem

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/11926758/a09aa492-a7c7-11e5-874f-5b699e9505b6.png)

This CSS is applied as default on the div where you instantiate the Kendo control on. These options should be overridden.

This `<div>` is inside our `chart.html` file, so our custom element is basically shielding this div from outside modification. We use our wrapper like this:

```
<au-kendo-chart>

</au-kendo-chart>
```

but can be seen as this:

```
<au-kendo-chart>
  <div ref="target"></div>
</au-kendo-chart>
```

We have to set a style on the `<div>` inside our custom element, so that it overrides the style provided by Telerik as default. This issue is about the height property, but the same goes for the background of [this issue](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/157)

**Comment by JeroenVinke** [comment]
### Option 1

Instead of initializing the chart on a `<div>` inside the custom element, we can initialize it on the custom element itself. That way, you can directly manipulate the css from the "outside".

```
this.widget = $(this.element).kendoChart(this.getOptions()).data('kendoChart');
```
_note: `this.element` is used instead of `this.target`(the div)_

Usage:
```
<template>
  <au-kendo-chart title.bind="{text: 'Gross Domestic product growth \n /GDP annual %/'}"
                  legend.bind="{position: 'bottom'}"
                  series-defaults.bind="seriesDefaults"
                  series.bind="series"
                  value-axis.bind="valueAxis"
                  category-axis.bind="categoryAxis"
                  tooltip.bind="tooltip"
                  style="height: 400px;">
  </au-kendo-chart>
</template>
```
_note the style attribute_

The style is indeed overridden:
![image](https://cloud.githubusercontent.com/assets/2189477/11927012/96fb8e68-a7c9-11e5-8094-06507b217818.png)

but the chart is a mess:

![image](https://cloud.githubusercontent.com/assets/2189477/11927020/aa0ecd26-a7c9-11e5-98e2-6a8d6f66a9c6.png)

**Comment by JeroenVinke** [comment]
Got it!! http://stackoverflow.com/a/22822461

`style="height: 600px; display: block"` is the magical combination :)

**Comment by JeroenVinke** [comment]
This is pretty amazing.

We can configure `display: block` on the "inside" of the custom element:

```
// chart.html
<template style="display: block;">
</template>
```

and just a height on the "outside" of the custom element:

```
<template>
  <au-kendo-chart style="height: 600px;">
  </au-kendo-chart>
</template>
```

Both styles are then merged together into:

```
  <au-kendo-chart style="display: block; height: 600px;">
  </au-kendo-chart>
```
