### ISSUE TITLE
Explain the rules for mapping between the view and view model

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#166]

**Comment by JeroenVinke** [comment]
Let's take the following pieces of code:

**The view:**
```
<template>
  <au-kendo-chart title.bind="{text: 'Spain windpower electricity production (GWh)'}"
                  legend.bind="legend"
                  data-source.bind="datasource"
                  series-defaults.bind="seriesDefaults"
                  series.bind="series"
                  value-axis.bind="valueAxis"
                  category-axis.bind="categoryAxis"
                  tooltip.bind="tooltip">
  </au-kendo-chart>
</template>
```

and the **view-model**

```
export class BindingToRemoteData {
    datasource = new kendo.data.DataSource({
      transport: {
        read: function(options) {
          return System.import('charts/funnel-charts/json/spain-electricity.json!json')
          .then(data => options.success(data));
        }
      },
      sort: {
          field: "year",
          dir: "desc"
      }
    });
```

By doing `<au-kendo-chart data-source.bind="datasource" />` in the view, you are binding the [`dataSource` property](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/src/chart/chart.js#L15) of the `au-kendo-chart` custom element, to the `datasource` property of the **view-model**.

The `datasource` property in the `BindingToRemoteData` **view-model** is an es7 [`class property`](https://github.com/jeffmo/es-class-fields-and-static-properties#proposed-syntax). This is essentially the same as initializing a property from the constructor of a class.

The kendo control is getting this `datasource` from our wrapper, and executes the `read` function of it:
``` 
        read: function(options) {
          return System.import('charts/funnel-charts/json/spain-electricity.json!json')
          .then(data => options.success(data));
        }
```
Kendo allows you to set the `read` property to a function callback. This way, you can decide for yourself where to get the data from, in this case, a json file loaded via SystemJS.

Notice the `options` parameter kendo passes into this function. When you are done loading your data (from anywhere), you are supposed to call the `success` method of this object and pass in the "data" kendo wants. We do this after we get the JSON back from SystemJS (the `data property`). This `data` variable (which contains our JSON data) is not stored, and thus lost, after we call `options.success(data)`.

Now, this is not the biggest reason your attempt failed. It turns out that kendo has put the funnel chart control in a different file. So, we needed to load the funnel javascript file [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/commit/ef9117c4863bc7b461de3c50979218d2fb5c6243#diff-33c9282a71c25eced45b8f75e16c9ba4R6).

**Comment by adriatic** [comment]
Trying to use this information to implement the **[funnel-charts basic use](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/funnel-charts/basic-use.html)** I realized that I am still troubled by the same issue - attributes mapping.

Here is more:
I am starting from my impression that the **[funnel-charts basic use](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/funnel-charts/basic-use.html)** sample is equivalent to the **[bullet-charts binding-to-local-data](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/bullet-charts/binding-to-local-data.html)** because they both: 
- have two (or more) charts side by side
- have the chart data defined in the Aurelia view-model file.

So, I tried to set the view and view models for both these cases the same way:
#### Funnel charts basic use view
```
            <au-kendo-chart title.bind="{text: 'October'}"
                              data-source.bind="octData"
                              legend.bind="legend"
                              series-defaults.bind="seriesDefaults"
                              series.bind="series_oct"
                              tooltip.bind="tooltip">
              </au-kendo-chart>
```
#### Funnel charts basic use view-model
```
export class BasicUse {

    octData = [
        {
            category: "Impressions ",
            value: 434823,
            color: "#0e5a7e"
        },{
            category: "Clicks",
            value: 356854,
            color: "#166f99"
        },{
            category: "Unique Visitors",
            value: 280022,
            color: "#2185b4"
        },{
            category: "Downloads",
            value: 190374,
            color: "#319fd2"
        },{
            category: "Purchases",
            value: 120392,
            color: "#3eaee2"
        }
    ];
...
```
expecting that the definition of the view attribute `data-source.bind="octData"` will  have as the consequence the "creation" of the **above presented** class attribute  `octData`

Having this octData array defined in the view-model, the remaining problem is to associate it with a specific `series`, which I hoped to ensure with the view's attribute definition `series.bind="series_oct"`. Given the KendoUI original code
```
                series: [{
                    type: "funnel",
                    data: data
                }]
```

where the second instance of the word data in `data: data` is actually a function argument, defined as `octData`, I created Aurelia view-model definition of the series object as
```
    series_oct = [{
        type: "funnel",
        data: octData
    }];
```
This however results with "octData not defined" error message.

Finally comparing this with the **[bullet-charts binding-to-local-data](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/bullet-charts/binding-to-local-data.html)** sample, which "succeeded on the first try" several days ago, I could see a single difference in the fact that in that definition of the view-model `series` object:

```
   series_mmHg = [{
        type: "verticalBullet",
        color: "#ffffff",
        opacity: .8,
        target: {
            color: "#ffffff"
        },
        currentField: "current",
        targetField: "target"
    }];
```

I specify the `series_mmHg` array's fields - which I do not do in the **[funnel-charts basic use](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/funnel-charts/basic-use.html)** sample.

I am trying to write this not just for my sake, but rather to expand our documentation a bit.

**Comment by JeroenVinke** [comment]
> expecting that the definition of the view attribute data-source.bind="octData" will have as the consequence the "creation" of the above presented class attribute octData

Adding `data-source.bind="octData"` will not cause the creation of the octData class attribute. The class attribute is created when the BasicUse view-model is instantiated (and the constructor is called). `data-source.bind="octData"` will bind the `dataSource` (`data-source` attribute) to the already existing `octData` property. 


> where the second instance of the word data in data: data is actually a function argument, defined as octData, I created Aurelia view-model definition of the series object as
```
    series_oct = [{
        type: "funnel",
        data: octData
    }];
```
This however results with "octData not defined" error message.

You can't reference a class property (`octData`) from another class property (`series_oct`) because they have not really been initialized yet. Initialization of class properties happen just before the constructor of the class is called. If you want to implement something like this, you would do it from the constructor:

```
export class BasicUse {
   octData = [{
            category: "Impressions ",
            value: 434823,
            color: "#0e5a7e"
        }
    ];

    constructor() {
        this.series_oct = [{
           type: "funnel",
           data: this.octData
       }];
   }
}
```

**Comment by JeroenVinke** [comment]
Seems to contain enough info to get someone going.
