### ISSUE TITLE
Explain the logic for handling user selections in the view

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#170]
The **[treemap basic-use](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/treemap/basic-use.html)** is a good model for this issue - how does the click on the "Vertical" radio button result with the change of the view

![image](https://cloud.githubusercontent.com/assets/2712405/11920911/1e0ad25a-a749-11e5-83ac-adbda9d87e87.png)

given the "event handlers" in the view model are

```javascript
  attached() {
    $(".options").bind("change", () => this.refresh());
  }

  refresh() {
    this.treemap.widget.setOptions({
      type: $("input[name=type]:checked").val()
    });
  }
```

**Comment by JeroenVinke** [comment]
I have put some more Aurelia magic in there ([view](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/treemap/basic-use.html), [view-model](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/charts/treemap/basic-use.js))

The radio buttons are bound to the bindable property "type": `@bindable type = 'squarified';`. Because we have a typeChanged() function defined, every time a user selects a different type, Aurelia calls the `typeChanged()` function. 

In this function we call [setOptions](http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart#methods-setOptions) on Kendo's control, passing in the selected type. The treemap seems to "rerender" when you call setOptions.

**Comment by adriatic** [comment]
As this is an important part of the demo-kendo app's doc set, I may come back to this with some additional questions once I start writing the documentation.

**Comment by JeroenVinke** [comment]
We have now plenty examples where there is interaction. A couple of them are in the progressbar samples. From a view-model you can now interact with a Kendo control. This is no different than using it in any javascript framework or with any other plugin. See the Telerik docs for more information
