### ISSUE TITLE
Remote data - telerik or our own service

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#228]
At the moment, most if not all of our samples that are fetching data from external data source are using the same trick - reading that data from a local json file that was created by manual connection to the original data source and persisting that data locally. 

Now, writing the docs, I do not find this a good practice as do not want to ask the user to do that. If the sample states "Binding to remote data" than that's what the sample ought to do.

I believe that we need to rework all these samples to either use Telerik's data or host that same service (which exists on Github as a repository) to our own service (probably also running on Github just like Kendo-Demo)

**Comment by JeroenVinke** [comment]
The service you mentioned [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/150) does not contain these JSON files ([link](https://github.com/telerik/kendo-ui-demos-service/search?utf8=%E2%9C%93&q=electricity))

Because of [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) we can't use these URL's:

- http://demos.telerik.com/kendo-ui/content/dataviz/js/spain-electricity.json
- https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/src/samples/charts/area-charts/json/spain-electricity.json

but we can use our demo site: http://aurelia-ui-toolkits.github.io/demo-kendo/src/samples/charts/area-charts/json/spain-electricity.json

However, this not what Telerik is doing: http://demos.telerik.com/kendo-ui/area-charts/remote-data-binding. They are loading a local file, via a relative path: 
```
read: {
    url: "../content/dataviz/js/spain-electricity.json",
    dataType: "json"
}
```



So we have three options:
1. we keep using SystemJS like we do now, so that path's calculated
```
      read: function(options) {
        return System.import('samples/charts/area-charts/json/spain-electricity.json!json')
        .then(data => options.success(data));
      }
```

2. we don't use SystemJS to generate the url for us, meaning we have to include the `src/` part
```
    transport: {
      read: 'src/samples/charts/area-charts/json/spain-electricity.json',
      type: 'json'
    },
```

3. we download json files from our demo site
```
    transport: {
      read: 'http://aurelia-ui-toolkits.github.io/demo-kendo/src/samples/charts/area-charts/json/spain-electricity.json',
      type: 'json'
    },
```

I wouldn't recommend option 3 because it would be a hassle to get new json files up there. Options 2 could also work, but we may have issues bundling (could be resolved I think)

**Comment by adriatic** [comment]
Great analysis of the situation, @JeroenVinke - let me try to respond in kind:

### Introduction
This issue starts with my proposal to [host our own instance of kendo-ui-demos service](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/150) -- which is motivated make our Aurelia KendoUI Bridge "more sophisticated" than original - particularly in the area of handling remote data, by augmenting [KendoUI datasource component](http://docs.telerik.com/kendo-ui/api/javascript/data/datasource). 

As I have not sufficiently studied neither Aurelia's own [data access features](https://gist.github.com/bryanrsmith/14caed2015b9c54e70c3), nor [KendoUI datasource component](http://docs.telerik.com/kendo-ui/api/javascript/data/datasource) my desire to improve the handling of remote data is at best something we should do at a later time or a pipe dream at worst. One could easily say that Aurelia is not concerned with remote data access and we are discussing it here because KendoUI is (concerned).

### Solution proposal

As I clearly mis-read the code
```
                dataSource: {
                    transport: {
                        read: {
                            url: "../content/dataviz/js/spain-electricity.json",
                            dataType: "json"
                        }
                    },
                    ...
```
as Telerik's attempt to "obfuscate" the actual URL referencing their server - meaning that the actual demo **really** reads a local file, I see no reason why not to stay with our existing solution which uses `SystemJS`

```
      read: function(options) {
        return System.import('samples/charts/area-charts/json/spain-electricity.json!json')
        .then(data => options.success(data));
      }
```

**Comment by JeroenVinke** [comment]
+1

**Comment by RedFeet** [comment]
Hi Adriatic & Jeroen,

It took me hours of trying and Googling to find out how to use the KendoUI Chart in your example with an external data file / service...

I agree with you both that an example/tutorial should demonstrate exactly _how_ to do it...
The example I found in the skeleton was an example how _not_ to do it...

Please update the skeletons like you agreed on in this discussion as it will help many people how to use KendoUI charts with Aurelia.

Thanks!

**Comment by adriatic** [comment]
Thanks for your comment @RedFeet.

All current examples showing how to use KendoUI widgets as Aurelia components are made as exact functional copies of the examples on **[Telerik's KendoUI site](http://demos.telerik.com/kendo-ui/). The reason for this approach is to facilitate the transition of existing Telerik user to Aurelia platform - and to a lot lesser extent to make "appeal" to Aurelia users, **initially**. We have a lot of plans to do what you are proposing, and we are doing the best we can, with the constraints that being fully employed elsewhere and doing this as a "labor of love".

**Comment by RedFeet** [comment]
Thanks for your swift reply!

I you would ask me what you just proposed to ask me, I would answer: "I'm willing to help/think/discuss, although contributing in GitHub is quite a new experience to me"

But to address the first part of your reply:
On this KendoUI page they show an example how to bind a KendoUI line chart to a remote data source: http://demos.telerik.com/kendo-ui/line-charts/remote-data-binding

But when I look in the Aurelia demo-kendo, I don't see how to bind to a remote data source, since a local .json file is imported (and will therefore be bundled, which is a not very dynamic nor very remote... ;-)

So I think the example here:
https://github.com/aurelia-ui-toolkits/demo-kendo/blob/master/src/samples/chart/line-charts/binding-to-remote-data.js#L5

needs to be modified to the proposed solution in your post above of 30 Dec 2015. So the demo truly demonstrates how to do Remote binding of a KendoUI (line) chart.

**Comment by adriatic** [comment]
Great timing - as I was just typing in the request to help us benefit from your experience, by saying what would you like instead of what you encountered. Now, I know precisely what you meant, we will publish some additional information on how to make things more dynamic. The restrictions we have:

1. We cannot directly fetch data from Telerik's web site (CORS issues)
2. We do not want to maintain a replica on some other site where we can solve CORS.

**Comment by RedFeet** [comment]
I understand (I also had to crush some CORS nuts, before getting it to work)

So the restriction is: "keep it local", since: ... CORS

I think Jeroen meant/proposed this solution as well: 
```
    dataSource: {
                    transport: {
                        read: {
                            url: "../content/dataviz/js/spain-electricity.json",
                            dataType: "json"
                        }
                    },
```
It shouldn't add CORS problems to the demo, since it addresses a local resource (with the same hostname) and it would be clear for anybody who wants to learn from it, since they would change the relative url to an absolute url referencing their desired datasource.
The syntax doesn't have to change in this example, only the url and therefore is it (in my opinion) a better example of binding to remote data than the current example:

`return System.import('samples/charts/area-charts/json/spain-electricity.json!json')`

**Comment by adriatic** [comment]
Agreed!
