### ISSUE TITLE
Button events sample does not show events anymore

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-kendoui-plugin#247]
The [Button Events sample](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/button/events) doesn't fill its console log anymore. Last time I looked at it (I think last week) it was still working.

**Comment by JeroenVinke** [comment]
Good catch. This is actually because we have an outdated dist folder of the plugin.

**Comment by adriatic** [comment]
I really do not think that the following advice is needed, so writing it only for completeness sake:

Creating the automatic deployment of the content of the **[bridge consumer sample application](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample)** to the github resident **[Aurelia KendoUI Components Catalog](http://aurelia-ui-toolkits.github.io/demo-kendo)** application is our highest priority and needs to be done before we release the Bridge.

Since that Catalog application has still issues related to bundling, I would propose that Jeroen leads that task - and I will drop everything else to help in any way.

**Comment by JeroenVinke** [comment]
this issue is fixed, but we will get started on the improvements mentioned above
