### ISSUE TITLE
Define the tooling and the process for testing

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#61]
I see no reason to handle this any differently than what Aurelia Core team does.

**Comment by charlespockert** [comment]
Agreed - we need to write tests that cover the binding and updating of binding properties. We do not need to test the Kendo controls themselves, rather that the data is correctly bound when changes are made to the properties on the wrapper viewmodels.

**Comment by JeroenVinke** [comment]
I have added a devDependency on aurelia-pal, aurelia-pal-browser and dependency injection, and I've also created this [unit test](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/test/unit/button.spec.js) to confirm the setup of our repo is working as it should

**Comment by JeroenVinke** [comment]
it would be great if we could use https://travis-ci.org/, but the problem is that our unit tests need kendo PRO to be installed, and this would mean travis-ci needs to have telerik credentials. i'm not sure if it's safe enough to do this

**Comment by JeroenVinke** [comment]
Travic ci is working now.

**Comment by adriatic** [comment]
Great!

**Comment by JeroenVinke** [comment]
# Unit testing and Travis CI setup

### KarmaJS
KarmaJS is the primary unit test runner. It is used to run unit tests during development, and is also used by Travis CI. The KarmaJS Test runner gets its configuration from [`karma.conf.js`](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/eb898f9bb3b6ee58235f81601c90783ba8a08802/karma.conf.js). Karma can be run in three ways: `karma start`, `gulp tdd` or `gulp test`.

- `karma start` has the same effect as `gulp tdd`.  
- `gulp tdd` runs the unit tests, and keeps running and watches for file changes. Every time a file changes, the unit tests are run again.  
- `gulp test` runs the unit tests, then exists

All tests in the `tests/unit` directory are run by Karma because it is defined in the `karma.conf.js` [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/fa1a4f24219dc772915ebee66739bb2c92a80a8b/karma.conf.js#L17)

### Travis CI
Travis CI is a continuous integration platform free of charge for open source projects. Travis CI can be enabled from their [website](https://travis-ci.org/). As soon as it is enabled, it looks for the [`.travis.yml`]((https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/eb898f9bb3b6ee58235f81601c90783ba8a08802/.travis.yml)) file in the root of the repository. Travis CI does a build after every commit, and with each pull request.

Some important parts of the [`.travis.yml`]((https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/eb898f9bb3b6ee58235f81601c90783ba8a08802/.travis.yml)) configuration file:
```
install:
  - npm install
  - jspm config registries.github.auth JSPM_GITHUB_AUTH_TOKEN
  - node_modules/.bin/jspm install
```

This tells Travis CI which commands to run as __setup__ for each build. First it installs the node modules via `npm install`, then configures the github endpoint of JSPM, and then it installs all the JSPM packages via `jspm install`. `JSPM_GITHUB_AUTH_TOKEN` is an [environment variable](https://docs.travis-ci.com/user/environment-variables/) that you can set on the [Travis CI website](https://travis-ci.org/).

The build itself is configured in the `scripts` section:

```
script:
  - npm run ci
```

This tells Travis CI to run the command `npm run ci`.

`run ci` is a command defined in the [package.json](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/eb898f9bb3b6ee58235f81601c90783ba8a08802/package.json#L22-L25), and because of this definition, the gulp task [`ci`](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/fa1a4f24219dc772915ebee66739bb2c92a80a8b/build/tasks/ci.js) will be run. 

The [`ci`](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/fa1a4f24219dc772915ebee66739bb2c92a80a8b/build/tasks/ci.js) gulp task contains:

```
var gulp = require('gulp');

gulp.task('ci', ['default']);
```

Which is just a reference to the [`default`](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/eb898f9bb3b6ee58235f81601c90783ba8a08802/build/tasks/default.js) gulp task:

```
var gulp = require('gulp');
var runSequence = require('run-sequence');

gulp.task('default', function(callback) {
  return runSequence(
    'lint',
    'build',
    'test',
    callback
  );
});
```

So in conclusion, when Travis CI does a build, it first runs `npm install`, `jspm config registries.github.auth` and `jspm install`, and then runs the actual build via `npm run ci`, which runs gulp tasks `lint`, `build`, and `test`.

### WallabyJS
[WallabyJS](http://wallabyjs.com/) is a test runner that runs tests while you are typing. It does not use Karma in any way, and gets its configuration from [wallaby.js](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/fa1a4f24219dc772915ebee66739bb2c92a80a8b/wallaby.js). Wallaby's test runner can't handle `@bindables`, so we need the bind-polyfill for that, which we load [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/fa1a4f24219dc772915ebee66739bb2c92a80a8b/wallaby.js#L11). Same goes for the MutationObserver, which [phantomjs 1 does not support](https://github.com/wallabyjs/public/issues/336#issuecomment-156889022). We load that polyfill [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/fa1a4f24219dc772915ebee66739bb2c92a80a8b/wallaby.js#L53)
