### ISSUE TITLE
Registry bower not found

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-plugin#65]
Charles proposed and verified the new method for "packaging" Kendo with Aurelia-KendoUI plugin. However, his instructions on how to deal with this new method:

Instructions for setting up the kendo bower git repo are:
```
npm install jspm-git --save-dev
jspm registry create kendo jspm-git
```
When it asks you for the repo root enter:
```
https://bower.telerik.com/
```
Then use
```
jspm install kendo-ui:bower-kendo-ui
```
I believe it will prompt you for credentials, though it didn't prompt me so......

* * *
My own experience: (**note that I elected to install jspm-git globally as I usually do**)
```
λ npm install -g jspm-git
C:\Users\Nikolaj\AppData\Roaming\npm
└─┬ jspm-git@0.4.2
  ├── ncp@2.0.0
  ├─┬ rimraf@2.4.3
  │ └─┬ glob@5.0.15
  │   ├─┬ inflight@1.0.4
  │   │ └── wrappy@1.0.1
  │   ├── inherits@2.0.1
  │   ├─┬ minimatch@3.0.0
  │   │ └─┬ brace-expansion@1.1.1
  │   │   ├── balanced-match@0.2.1
  │   │   └── concat-map@0.0.1
  │   ├── once@1.3.2
  │   └── path-is-absolute@1.0.0
  ├── rsvp@3.1.0
  ├── semver@4.3.6
  ├─┬ temp@0.8.3
  │ ├── os-tmpdir@1.0.1
  │ └── rimraf@2.2.8
  ├── url-join@0.0.1
  ├── valid-url@1.0.9
  └─┬ which@1.2.0
    └─┬ is-absolute@0.1.7
      └── is-relative@0.1.3
```
Then:
```
Enter the base URL of your git server e.g. https://code.mycompany.com/git/:https://bower.telerik.com/
Set advanced configurations? [no]:
ok   Registry kendo configured successfully.
```
At this point I went to install `bower-kendo-ui` and things did not go well
```
λ jspm install kendo-ui:bower-kendo-ui                                                  
                                                                                        
warn Running jspm globally, it is advisable to locally install jspm via npm install jspm
ve-dev.                                                                                 
                                                                                        
err  Registry bower not found.                                                          
                                                                                        
err  Unable to load registry bower                                                      
                                                                                        
warn Installation changes not saved.                                                    
```
At this point, I nuked my whole `C:\Users\Nikolaj\AppData\Roaming\npm` - assuming that it has some garbage that stops me from following the four instruction on how to install that darn kendo.

**Comment by charlespockert** [comment]
Sorry there was a typo on the previous, it should be:

```
jspm install kendo-ui=kendo:bower-kendo-ui
```

Basically jspm-git is just a generic git endpoint for JSPM (i.e. it tells JSPM how to locate package files and where to download them from). An endpoint specifies the place to connect to, so we are creating a connection to Telerik's git repo and naming the endpoint "kendo" so we can use it to install from there.

The format of the above command is:

```
jspm install <package-alias>=<endpoint-name>:<repo-name>
````

You could just call the endpoint `telerik` - it would probably be a more accurate moniker but since we only need to install kendo, I've just called it kendo. Maybe in the docs this should be "telerik", it really doesn't matter though, what's important is that you install the Kendo libraries with the `kendo-ui` alias as that's what our plugin will expect to find in your application.

**Comment by adriatic** [comment]
See https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/71 for a summary of this and related issues which are all closed now
